language: objective-c
osx_image: xcode7

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=AlamofireObjectMapper.xcworkspace
  matrix:
    - SCRIPT="xcodebuild -workspace $XCODE_WORKSPACE -scheme AlamofireObjectMapper\ iOS -sdk iphonesimulator test"
    - SCRIPT="xcodebuild -workspace $XCODE_WORKSPACE -scheme AlamofireObjectMapper\ OSX test"
    # - SCRIPT="xctool -workspace $XCODE_WORKSPACE -scheme AlamofireObjectMapper\ iOS -sdk iphonesimulator test"
    # - SCRIPT="xctool -workspace $XCODE_WORKSPACE -scheme AlamofireObjectMapper\ OSX test"

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script: $SCRIPT

notifications:
  email: false